### ISSUE TITLE
Move all color manipulation logic to `Palette` class

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/chromabox#42]
- [`const variants: Swatch[] = $derived.by(() => { ... }`](https://github.com/fmaclen/chromabox/blob/main/src/routes/ColorCard.svelte#L24-L50)
- [`paletteContext.colors = DEFAULT_COLOR_PALETTE`](https://github.com/fmaclen/chromabox/blob/main/src/routes/%2Bpage.svelte#L15-L20)

**Comment by GregoMac1** [comment]
🙋‍♂️ I am currently working on this in my WIP implementation in #39. I hadn't seen this issue, but I had also thought that it was a necessary change.
